spring.application.name=quickstart
server.port=8080

kurrentdb.connection-string=${KURRENTDB_CONNECTION_STRING:kurrentdb://localhost:2113?tls=false}

spring.datasource.url=jdbc:postgresql://localhost:5432/quickstart
spring.datasource.username=quickstart
spring.datasource.password=quickstart
spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml

management.endpoint.health.show-components=always
