spring.application.name=Platform QuickStart

spring.datasource.url=jdbc:postgresql://localhost:5432/quickstart
spring.datasource.username=quickstart
spring.datasource.password=quickstart

spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml